# traefik.yml
global:
  checkNewVersion: true
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: false # 禁用不安全的dashboard访问

entryPoints:
  metrics:
    address: ":8082"
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    http:
      tls:
        certificates:
          - certFile: /etc/traefik/certs/azel.icu.crt
            keyFile: /etc/traefik/certs/azel.icu.key

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    exposedByDefault: false
    network: app_network

  file:
    directory: /etc/traefik/dynamic
    watch: true

      #log:
      #  level: DEBUG
      #  filePath: "/var/log/traefik/traefik.log"

accessLog:
  filePath: "/var/log/traefik/access.log"
  bufferingSize: 100

metrics:
  prometheus:
    entryPoint: metrics
