apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 基础资源
resources:
- ../../base/namespace.yaml
- ../../base/configmap.yaml
- ../../base/secret.yaml
- ../../base/postgres.yaml
- ../../base/deployment.yaml
- ../../base/service.yaml
- ../../base/ingress.yaml
- ../../base/traefik-config.yaml
- ../../base/cert-manager.yaml
- prod-middlewares.yaml

# 命名空间
namespace: final-ddd-prod

# 名称前缀
namePrefix: prod-

# 标签
commonLabels:
  environment: prod
  version: stable

# 镜像替换
images:
- name: final-ddd
  newTag: stable

# 配置补丁
patchesStrategicMerge:
- patches.yaml

# ConfigMap 生成器 - PostgreSQL 优先配置
configMapGenerator:
- name: app-config
  behavior: merge
  literals:
  - APP_ENV=production
  - LOG_LEVEL=info
  - DB_NAME=final_ddd
  - DB_HOST=postgres-prod
  - DB_PORT=5432
  - DB_USER=postgres
  - DB_SSL_MODE=require
  - DB_MAX_OPEN=50
  - DB_MAX_IDLE=10
  files:
  - config.yml=prod-config.yml

# Secret 生成器 - PostgreSQL 优先 (生产环境应该使用外部密钥管理)
secretGenerator:
- name: app-secrets
  behavior: merge
  literals:
  - database-url=postgresql://postgres:${POSTGRES_PASSWORD}@prod-postgres-service:5432/final_ddd?sslmode=require
  - db-password=${POSTGRES_PASSWORD}
  - jwt-secret=${JWT_SECRET}
  - redis-password=${REDIS_PASSWORD}