# configs/config.yml
app:
  name: final-ddd
  port: 9999
  env: release #, debug # or release, test

database:
  type: postgres # or mysql, sqlite
  user: postgres
  password: password
  host: postgres
  port: 5432
  name: test
  path: ./sqlite_data

jwt:
  key: "123456"

redis:
  host: redis
  port: 6379
  password: ""
  db: 0

log:
  level: info
  format: json
