# configs/config.yml - PostgreSQL 优先配置
app:
  name: final-ddd
  port: 8080
  env: ${APP_ENV:production}

# PostgreSQL 优先数据库配置
database:
  # 推荐使用 URL 方式（优先级最高）
  url: ${DATABASE_URL:postgresql://postgres:password@postgres:5432/final_ddd?sslmode=disable}
  
  # 或者使用分离的字段配置
  host: ${DB_HOST:postgres}
  port: ${DB_PORT:5432}
  name: ${DB_NAME:final_ddd}
  user: ${DB_USER:postgres}
  password: ${DB_PASSWORD:password}
  ssl_mode: ${DB_SSL_MODE:disable}
  
  # 连接池配置
  pool:
    max_open: ${DB_MAX_OPEN:25}
    max_idle: ${DB_MAX_IDLE:5}
    max_lifetime: ${DB_MAX_LIFETIME:300s}
  
  # 向后兼容字段（已弃用，但保留支持）
  type: ${DB_TYPE:postgres}  # 已弃用：优先使用 url 或具体字段
  
  # 备用数据库配置（可选，用于测试）
  fallback:
    mysql: ${MYSQL_URL:}
    sqlite: ${SQLITE_PATH:./data/app.db}

jwt:
  key: ${JWT_SECRET:default_secret_key}

redis:
  host: ${REDIS_HOST:redis}
  port: ${REDIS_PORT:6379}
  password: ${REDIS_PASSWORD:}
  db: 0

log:
  level: ${LOG_LEVEL:info}
  format: json
  output: ${LOG_OUTPUT:stdout}  # stdout, file, both
  file_path: ${LOG_FILE_PATH:/var/log/app/app.log}
  max_size: ${LOG_MAX_SIZE:100}      # MB
  max_backups: ${LOG_MAX_BACKUPS:5}  # 保留文件数
  max_age: ${LOG_MAX_AGE:30}         # 保留天数
  compress: ${LOG_COMPRESS:true}     # 压缩旧日志

# 监控配置
monitoring:
  # Prometheus metrics
  metrics:
    enabled: ${METRICS_ENABLED:true}
    port: ${METRICS_PORT:9090}
    path: ${METRICS_PATH:/metrics}

  # 日志监控 (Loki)
  loki:
    enabled: ${LOKI_ENABLED:false}
    endpoint: ${LOKI_ENDPOINT:http://loki:3100}

  # 链路追踪 (可选)
  tracing:
    enabled: ${TRACING_ENABLED:false}
    jaeger_endpoint: ${JAEGER_ENDPOINT:http://jaeger:14268/api/traces}
