# configs/config.yml
app:
  name: final-ddd
  port: 9999
  env: release #, debug # or release, test

database:
  type: mysql # or postgres, sqlite
  user: root
  password: newroot
  host: 127.0.0.1
  port: 3306
  name: test1
  path: ./sqlite_data

jwt:
  key: "123456"

redis:
  host: redis
  port: 6379
  password: ""
  db: 0

log:
  level: info
  format: json
