apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
  labels:
    grafana_datasource: "1"
data:
  datasources.yaml: |
    apiVersion: 1
    
    deleteDatasources:
      - name: Prometheus
        orgId: 1
      - name: Loki
        orgId: 1
    
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        orgId: 1
        url: http://prometheus-service:9090
        basicAuth: false
        isDefault: true
        version: 1
        editable: true
        jsonData:
          httpMethod: POST
          queryTimeout: 60s
          timeInterval: 15s
        
      - name: Loki
        type: loki
        access: proxy
        orgId: 1
        url: http://loki-service:3100
        basicAuth: false
        isDefault: false
        version: 1
        editable: true
        jsonData:
          maxLines: 1000
          derivedFields:
            - datasourceUid: prometheus
              matcherRegex: "traceID=(\\w+)"
              name: TraceID
              url: "$${__value.raw}"
        
      - name: AlertManager
        type: alertmanager
        access: proxy
        orgId: 1
        url: http://alertmanager-service:9093
        basicAuth: false
        isDefault: false
        version: 1
        editable: true
        jsonData:
          implementation: prometheus