apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 基础资源
resources:
- ../../base/namespace.yaml
- ../../base/configmap.yaml
- ../../base/secret.yaml
- ../../base/postgres.yaml
- ../../base/deployment.yaml
- ../../base/service.yaml
- ../../base/ingress.yaml
- ../../base/traefik-config.yaml
- ../../base/cert-manager.yaml
- dev-middlewares.yaml

# 命名空间
namespace: final-ddd-dev

# 名称前缀
namePrefix: dev-

# 标签
commonLabels:
  environment: dev
  version: latest

# 镜像替换
images:
- name: final-ddd
  newTag: dev-latest

# 配置补丁
patchesStrategicMerge:
- patches.yaml

# ConfigMap 生成器 - PostgreSQL 优先配置
configMapGenerator:
- name: app-config
  behavior: merge
  literals:
  - APP_ENV=development
  - LOG_LEVEL=debug
  - DB_NAME=final_ddd_dev
  - DB_HOST=localhost
  - DB_PORT=5432
  - DB_USER=postgres
  - DB_SSL_MODE=disable
  - DB_MAX_OPEN=10
  - DB_MAX_IDLE=2
  files:
  - config.yml=dev-config.yml

# Secret 生成器 - PostgreSQL 优先
secretGenerator:
- name: app-secrets
  behavior: merge
  literals:
  - database-url=postgresql://postgres:dev_password@dev-postgres-service:5432/final_ddd_dev?sslmode=disable
  - db-password=dev_password
  - jwt-secret=dev_jwt_secret_key_123456